//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataModelConnection : DbContext
    {
        public DataModelConnection()
            : base("name=DataModelConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Type> Category_Type { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Privacy_Type> Privacy_Type { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Event_User> Event_User { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Group_User> Group_User { get; set; }
        public virtual DbSet<User_Message> User_Message { get; set; }
    
        public virtual ObjectResult<GetDeletedMessages_SP_Result> GetDeletedMessages_SP(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDeletedMessages_SP_Result>("GetDeletedMessages_SP", usernameParameter);
        }
    
        public virtual ObjectResult<GetRecievedMessages_SP_Result> GetRecievedMessages_SP(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecievedMessages_SP_Result>("GetRecievedMessages_SP", usernameParameter);
        }
    
        public virtual ObjectResult<GetSentMessages_SP_Result> GetSentMessages_SP(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSentMessages_SP_Result>("GetSentMessages_SP", usernameParameter);
        }
    }
}
