//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Event_User = new HashSet<Event_User>();
        }
    
        public int Event_Id { get; set; }
        public int Location_Id { get; set; }
        public int Category_Id { get; set; }
        public string Created_By { get; set; }
        public int Privacy_Type_Id { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Image_Url { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deletion_Date { get; set; }
        public string Name { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_User> Event_User { get; set; }
        public virtual User User { get; set; }
        public virtual Location Location { get; set; }
        public virtual Privacy_Type Privacy_Type { get; set; }
    }
}
