//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public string Friend_Username { get; set; }
        public string Friended_Username { get; set; }
        public int Category_Id { get; set; }
        public Nullable<System.DateTime> Accepted_Date { get; set; }
        public int Firend_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
