//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Events = new HashSet<Event>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Location_Id { get; set; }
        public decimal Longitude { get; set; }
        public decimal Lattitude { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type_Id { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public decimal Popularity { get; set; }
        public bool Approved { get; set; }
        public string Zipcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Type Type { get; set; }
        public virtual Town Town { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
