//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.User_Message = new HashSet<User_Message>();
        }
    
        public int Message_Id { get; set; }
        public string Subject { get; set; }
        public string Message1 { get; set; }
        public System.DateTime Sent_Date { get; set; }
        public Nullable<System.DateTime> Read_Date { get; set; }
        public Nullable<System.DateTime> Deletion_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Message> User_Message { get; set; }
    }
}
