//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Photos_Id { get; set; }
        public int Visit_Id { get; set; }
        public string Image_Url { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Like { get; set; }
        public int Dislike { get; set; }
        public int Report { get; set; }
        public decimal Popularity { get; set; }
        public Nullable<int> Privacy_Type_Id { get; set; }
        public Nullable<System.DateTime> Deletion_Date { get; set; }
    
        public virtual Privacy_Type Privacy_Type { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
