//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Message
    {
        public string Sender { get; set; }
        public string Reciever { get; set; }
        public int Message_Id { get; set; }
        public int User_Message_Id { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
